/*
Code automatically generated by asn1scc tool
*/
#include <limits.h>
#include <string.h>
#include <math.h>
#include "Context-aruco-marker-detector.h"


const asn1SccContext_aruco_marker_detector aruco_marker_detector_ctxt = {
    .capture_device_id = 0,
    .marker_size = 6.70000000000000040000E-002,
    .draw_augmented_image = 1
};


flag asn1SccContext_aruco_marker_detector_Equal(const asn1SccContext_aruco_marker_detector* pVal1, const asn1SccContext_aruco_marker_detector* pVal2)
{
	flag ret=TRUE;

    ret = (pVal1->capture_device_id == pVal2->capture_device_id);

    if (ret) {
        ret = (pVal1->marker_size == pVal2->marker_size);

        if (ret) {
            ret = (pVal1->draw_augmented_image == pVal2->draw_augmented_image);

        }
    }
	return ret;

}

void asn1SccContext_aruco_marker_detector_Initialize(asn1SccContext_aruco_marker_detector* pVal)
{


	/*set capture_device_id */
	asn1SccT_Int32_Initialize((&(pVal->capture_device_id)));
	/*set marker_size */
	asn1SccT_Double_Initialize((&(pVal->marker_size)));
	/*set draw_augmented_image */
	asn1SccT_Int32_Initialize((&(pVal->draw_augmented_image)));
}

flag asn1SccContext_aruco_marker_detector_IsConstraintValid(const asn1SccContext_aruco_marker_detector *pVal, int* pErrCode)
{
    flag ret = TRUE;
	
    ret = ((-2147483648LL <= pVal->capture_device_id) && (pVal->capture_device_id <= 2147483647LL));
    *pErrCode = ret ? 0 :  ERR_CONTEXT_ARUCO_MARKER_DETECTOR_CAPTURE_DEVICE_ID;
    if (ret) {
        ret = ((-1.79769313486231570000E+308 <= pVal->marker_size) && (pVal->marker_size <= 1.79769313486231570000E+308));
        *pErrCode = ret ? 0 :  ERR_CONTEXT_ARUCO_MARKER_DETECTOR_MARKER_SIZE;
        if (ret) {
            ret = ((-2147483648LL <= pVal->draw_augmented_image) && (pVal->draw_augmented_image <= 2147483647LL));
            *pErrCode = ret ? 0 :  ERR_CONTEXT_ARUCO_MARKER_DETECTOR_DRAW_AUGMENTED_IMAGE;
        }
    }

	return ret;
}

